project:
  type: website
  output-dir: ../docs
  preview:
    port: 9999
  render:
    - "*.qmd"
    - "!**/wip/*"
    - "!**/prep/*"

external-env: true
jupyter: w26-201b

execute:
  python: ".venv/bin/python"
  external: true
  cache: true
  freeze: auto

website:
  announcement:
    icon: megaphone-fill
    dismissable: false
    content: "**Site Updates:** Week 10 Slides"
    type: success
    position: below-navbar
  title: "PSYC 201B"
  repo-url: https://github.com/psyc-201/w26-201b
  navbar:
    logo: logo25.png
    search: true
    tools:
      - icon: github
        href: https://github.com/psyc-201/w26-201b
    left:
      - text: Schedule
        href: schedule.qmd
      - text: Final Project
        href: weeks/final/project.qmd
      - text: Open Datasets
        href: datasets.qmd
      - text: Glossary
        href: guides/terminology.qmd
      - text: Guides & Resources
        menu:
          - guides/git-guide.qmd
          - guides/classroom-guide.qmd
          - guides/python-resources.qmd
          - guides/notation.qmd
          - guides/formulas.qmd
      - text: Anonymous Feedback
        href: https://forms.gle/eXfTXVqYxCCFbv9c7
      - text: Previous course versions
        href: https://psyc201b.github.io/PSYC-201B/

  sidebar:
    - id: weeks
      title: "Week-by-Week"
      style: docked
      contents:
        - section: "Week 1"
          contents:
            - text: "Overview"
              href: weeks/01/index.qmd
            - text: '"Pre-flight" Lab Setup'
              href: weeks/01/lab/index.qmd
            - text: "Python Fundamentals"
              href: weeks/01/lab/python-fundamentals.qmd
            - text: "Polars (dataframes) Crash Course"
              href: weeks/01/lab/polars-crash-course.qmd
        - section: "Week 2"
          contents:
            - text: "Overview"
              href: weeks/02/index.qmd
            - text: "Seaborn (plotting) Crash Course"
              href: weeks/02/lab/seaborn-crash-course.qmd
            - text: "EDA Workflows"
              href: weeks/02/lab/eda-workflows.qmd
        - section: "Week 3"
          contents:
            - text: "Overview"
              href: weeks/03/index.qmd
        - section: "Week 4"
          contents:
            - text: "Overview"
              href: weeks/04/index.qmd
            - text: "Simulation & Bootstrapping"
              href: weeks/04/lab/01-sampling.qmd
            - text: "Permutation & Cross-Validation"
              href: weeks/04/lab/02-explanation-prediction.qmd
        - section: "Week 5"
          contents:
            - text: "Overview"
              href: weeks/05/index.qmd
        - section: "Week 6"
          contents:
            - text: "Overview"
              href: weeks/06/index.qmd
            - text: "Regression Basics"
              href: weeks/06/lab/01-glm-basics.qmd
            - text: "Categorical Predictors"
              href: weeks/06/lab/02-categorical-coding.qmd
        - section: "Week 8"
          contents:
            - text: "Overview"
              href: weeks/08/index.qmd
        - section: "Week 9"
          contents:
            - text: "Overview"
              href: weeks/09/index.qmd
        - section: "Week 10"
          contents:
            - text: "Overview"
              href: weeks/10/index.qmd

bibliography: references.bib

glossary:
  path: glossary.yml
  popup: click
  show: true

format:
  html:
    theme:
      - cosmo
    css: assets/custom.css
    code-fold: true
    code-copy: true
    code-line-numbers: true
    toc: true
    toc-depth: 4
