---
sidebar: weeks
title: "Schedule"
---

:::{.callout-note}
The last date to `commit` and `push` any updates to previous labs, HWs, and challenges for mastery-based grading is **March 20th by midnight**.
:::

::: {.completed-weeks}
| Week | Date | Content | Assignment Due? |
|------|------------|--------------------------------------------------------------------|---------------------------------------------------------------|
| 1 | Mon Jan 5 | Course Intro | _N/A_ |
| 1 | Tues Jan 6 | Laptop setup, Github Clasroom workflow, `quarto`, Python notebooks | `push` [lab 01](/weeks/01/#materials) at least once |
| 1 | Wed Jan 6 | Python essentials, dataframes, meet `polars` | `push` _updated_ [lab 01](/weeks/01/#materials) at least once |
| 2 | Mon Jan 12 | Two cultures of statistics, sampling theory | **skim readings for Wed Jan 14** |
| 2 | Tues Jan 13 | Data visualization, meet `seaborn` & `matplotlib` | `push` lab 02 at least once |
| 2 | Wed Jan 14 | What is a model? Model-based thinking | `push` **HW 1 by Tues Jan 20** |
| _3_ | _Mon Jan 19_ | _No class holiday_ | - |
| 3 | Tues Jan 20 | HW 1 review; Python Q&A | `push` **HW 1 by 1pm** |
| 3 | Wed Jan 21 | Hypothesis testing as model comparison | - |
| 4 | Mon Jan 26 | Statistics for Hackers: Resampling approaches | _N/A_ |
| 4 | Tues Jan 27 | Monte-carlo simulation & bootstrap resampling | `push` lab 03 at least once |
| 4 | Wed Jan 28 | Permutation testing & cross-validation | `push` **HW 2 by Midnight Mon Feb 1** |
| _5_ | _Mon Feb 2_ | _No class, prospective interviews_ | _N/A_ |
| 5 | Tues Feb 3 | HW 2 review; GLM Foundations | - |
| 5 | Wed Feb 4 | GLM II | **checkout [linear algebra materials](/weeks/05/#mentioned-references) for Mon Feb 9** |
| 6    | Mon Feb 9    | GLM III                                                | -                                                           |
| 6    | Tues Feb 10  | Meet `bossanova`                                       | `push` lab at least once                                    |
| 6    | Wed Feb 11   | **[Final Project](/weeks/final/project.qmd) planning** | `push` lab at least once                      |
| _7_  | _Mon Feb 16_ | _No class holiday_                                     | -                                                           |
| _7_    | _Tues Feb 17_  | _Class cancelled_                                  | -                                                           |
| _7_    | _Wed Feb 18_   | _Class cancelled_                                  |                               -                            |
| 8    | Mon Feb 23   | GLM IV                                                 | Review readings for tomorrow's discussion                   |
| 8    | Tues Feb 24  | GLM Discussion & Lab                                   | -                                     |
| 8    | Wed Feb 25   | GLM VI                                                 | `push` lab at least once                                    |
| 9    | Mon Mar 2    | Marginal effects & GLMs                                | -                                                           |
| 9    | Tues Mar 3   | Lab Review                                             | **Final Project Proposal Due**                              |
| 9    | Wed Mar 4    | Lab Logistic Regression                                | `push` **`challenge.py` notebook by Midnight Mon Mar 9**    |
:::

| Week | Date         | Content                                                | Assignment Due?                                             |
| ---- | ------------ | ------------------------------------------------------ | ----------------------------------------------------------- |
| 10   | Mon Mar 9    | LMMs                                                   | -                                                |
| 10   | Tues Mar 10  | LMMs lab; Proposal Review                              | -                                                 |
| 10   | Wed Mar 11   | Course Wrap-Up; final project time                     | -                                                  |
| FW   | Tues Mar 17  | Final Project Deadline                                 | `push` **[Final Project](/weeks/final/project.qmd)** |
| FW   | Friday Mar 19 | Last day to `push` to any labs/hws/challenges          | -       |

: _Tentative schedule_