---
sidebar: weeks
title: Python Resources
---

## Basics

- [Terminal commands cheatsheet](https://www.git-tower.com/blog/media/pages/posts/command-line-cheat-sheet/64337e6bae-1733170994/command-line-cheat-sheet-large01.avif)
- [Python basics cheatsheet](https://media.datacamp.com/legacy/image/upload/v1694526244/Marketing/Blog/Python_Basics_Cheat_Sheet-updated.pdf)
- [Python interactive reference](https://www.pythoncheatsheet.org/cheatsheet/basics)
- [Python for R users](https://cran.r-project.org/web/packages/reticulate/vignettes/python_primer.html)

## Python libraries we'll use

:::{callout-tip}
When you're working in Python it can be *super* helpful to regularly refer to these resources. Remember that you can always use any `API reference` link below to get a comprehensive list of *all* the functions and methods in a library - a bit nicer than only relying on `?` in your notebook.
:::

Throughout the course we''ll make use of the following Python libraries in case you want quickly reference their documentation:

- [`polars`](https://docs.pola.rs/user-guide/getting-started/)
- [`seaborn`](https://seaborn.pydata.org/)
- [`matplotlib`](https://matplotlib.org/)
- [`scipy`](https://scipy.org/) 
- [`numpy`](https://numpy.org/doc/stable/index.html)
- [`bossanova`]()
- [`scikit-learn`](https://scikit-learn.org/stable/)

### `polars` - DataFrames & tidy data analysis

- [Polars user guide](https://docs.pola.rs/)
- [Polars API reference](https://docs.pola.rs/api/python/dev/reference/index.html)
- [Tidyverse and Polars side-by-side](https://robertmitchellv.com/blog/2022-07-r-python-side-by-side/r-python-side-by-side.html)
- [Polars Rgonomic patterns](https://www.emilyriederer.com/post/py-rgo-polars/)
- [Pandas - alternative DataFrame library we're NOT using](https://pandas.pydata.org/docs/index.html)

### `seaborn` - high-level statistical visualizations

- [Seaborn user guide](https://seaborn.pydata.org/tutorial.html)
- [Seaborn API](https://seaborn.pydata.org/api.html)
- [Seaborn cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Seaborn_Cheat_Sheet.pdf)

### `matplotlib` - lower-level plot customization

- [Matplotlib user guide](https://matplotlib.org/stable/users/index.html)
- [Matplotlib API reference](https://matplotlib.org/stable/api/index.html)
- [Matplotlib tutorials](https://matplotlib.org/stable/tutorials/index.html)
- [Matplotlib cheatsheets](https://matplotlib.org/cheatsheets/)

### `scipy` - scientific functions & basic stats

- [SciPy user guide](https://docs.scipy.org/doc/scipy/tutorial/index.html)
- [SciPy API reference](https://docs.scipy.org/doc/scipy/reference/index.html)
- [Summary statistics](https://docs.scipy.org/doc/scipy/reference/stats.html#summary-statistics)
- [Resampling, i.e. montecarlo, bootstrap, permutation](https://docs.scipy.org/doc/scipy/reference/stats.html#resampling-and-monte-carlo-methods)
- [Hypothesis testing](https://docs.scipy.org/doc/scipy/reference/stats.html#hypothesis-tests-and-related-functions)

### `numpy` - arrays, matrices, and linear algebra

- [Numpy tutorials](https://numpy.org/numpy-tutorials/)
- [Numpy API reference](https://numpy.org/doc/stable/reference/index.html)
- [Numpy Cheatsheet](https://media.datacamp.com/legacy/image/upload/v1676302459/Marketing/Blog/Numpy_Cheat_Sheet.pdf)
- [Numpy for MATLAB users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)

### `bossanova` - intuitive formula-based statistical modeling

- [Documentation & tutorials]()

### `scikit-learn` - machine-learning

- [Scikit-learn cheatsheet](https://media.datacamp.com/legacy/image/upload/v1676302389/Marketing/Blog/Scikit-Learn_Cheat_Sheet.pdf)
- [Supervised learning](https://scikit-learn.org/stable/supervised_learning.html)
- [Decomposition](https://scikit-learn.org/stable/modules/decomposition.html)
- [Model selection & evaluations](https://scikit-learn.org/stable/model_selection.html)
